spring.datasource.url=jdbc:postgresql://database:5432/reputation
spring.datasource.username=reputation
spring.datasource.password=reputation_password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

canton.grpc.host=canton-sandbox
canton.grpc.port=6865