daml_dir := "daml"
dar       := daml_dir / ".daml/dist/reputation-1.0.0.dar"
host      := "localhost"
port      := "6865"

start:
    docker compose up

daml-build:
    cd {{daml_dir}} && daml build

canton-test: daml-build
    docker exec canton-sandbox daml script \
        --dar /app/dist/reputation-1.0.0.dar \
        --script-name TestScript:main \
        --ledger-host localhost \
        --ledger-port 6865
